# Generated by Django 4.0.4 on 2022-04-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
