# Generated by Django 3.1 on 2022-04-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_product', '0005_auto_20220421_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritesitem',
            name='favourites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user_product.favourites', verbose_name='Избранное'),
        ),
    ]
