# Generated by Django 3.1 on 2022-04-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_feature',
            name='value_float',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='product_feature',
            name='value_text',
            field=models.TextField(blank=True, null=True, verbose_name='Значение'),
        ),
    ]
