# Generated by Django 3.1 on 2022-04-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220403_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_feature',
            old_name='feature_id',
            new_name='feature',
        ),
        migrations.RenameField(
            model_name='product_feature',
            old_name='product_id',
            new_name='product',
        ),
    ]
