# Generated by Django 3.1 on 2022-04-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20220403_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/%Y/%m/%d/', verbose_name='Лого Бренда'),
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/%Y/%m/%d/', verbose_name='Лого Категории'),
        ),
    ]
