# Generated by Django 3.1 on 2022-04-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20220405_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='category_id',
            new_name='category',
        ),
    ]
