# Generated by Django 3.1 on 2022-04-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedbacks/%Y/%m/%d/', verbose_name='Изображения')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.feedback', verbose_name='Ответы')),
            ],
        ),
    ]
