# Generated by Django 3.1 on 2022-04-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_feedbackimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Feature',
            new_name='ProductFeature',
        ),
    ]
