# Generated by Django 3.1 on 2022-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20220418_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания отзыва'),
        ),
    ]
