# Generated by Django 3.1 on 2022-04-19 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0014_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='feedbackimage',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.feedback', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='feedbackimage',
            name='image',
            field=models.FileField(upload_to='feedbacks/%Y/%m/%d/', verbose_name='Изображения'),
        ),
    ]
