# Generated by Django 3.1 on 2022-04-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20220419_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
