# Generated by Django 3.1 on 2022-04-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_delete_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackimage',
            name='feedback',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='FeedbackImage',
        ),
    ]
