# Generated by Django 4.0.4 on 2022-04-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, verbose_name='Общий рейтинг'),
        ),
    ]
