# Generated by Django 4.0.4 on 2022-04-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_product_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='Общий рейтинг'),
        ),
    ]
